#!/usr/bin/env bash
# ============================================================================
# Zolai Core - Production Installer
# ============================================================================
# One-command install & deploy for fresh servers.
#
# Usage: curl -fsSL https://raw.githubusercontent.com/Zolai-AI/zolai-core/main/install.sh | bash
# Or:    ./install.sh [options]
#
# Options:
#   --domain DOMAIN       Set domain (default: api.zolai.space)
#   --email EMAIL         Admin email for Let's Encrypt
#   --no-ssl              Skip SSL/TLS (dev only)
#   --skip-build          Skip Docker build (use existing image)
#   --branch BRANCH       Git branch to deploy (default: main)
#   --help                Show help
#
# Prerequisites:
#   - Ubuntu 22.04+ / Debian 12+
#   - Docker 24+ & Docker Compose v2
#   - Port 80/443 open for Let's Encrypt
#   - DNS A record pointing to this server
# ============================================================================

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────
REPO="https://github.com/Zolai-AI/zolai-core.git"
BRANCH="main"
INSTALL_DIR="/opt/zolai-core"
DOMAIN="api.zolai.space"
EMAIL=""
SKIP_SSL=false
SKIP_BUILD=false

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log() { echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $*"; }
ok() { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err() { echo -e "${RED}[ERR]${NC} $*"; }

usage() { grep '^#' "$0" | cut -c4-; exit 0; }

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain) DOMAIN="$2"; shift 2 ;;
        --email) EMAIL="$2"; shift 2 ;;
        --no-ssl) SKIP_SSL=true; shift ;;
        --skip-build) SKIP_BUILD=true; shift ;;
        --branch) BRANCH="$2"; shift 2 ;;
        --help) usage ;;
        *) err "Unknown: $1"; usage ;;
    esac
done

# ── Checks ──────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || { err "Run as root (sudo)"; exit 1; }
command -v docker >/dev/null || { err "Install Docker first"; exit 1; }
docker compose version >/dev/null 2>&1 || { err "Docker Compose v2 required"; exit 1; }
[[ "$DOMAIN" != "api.zolai.space" || -n "$EMAIL" ]] || { err "Set --email for Let's Encrypt"; exit 1; }

log "Installing Zolai Core to $INSTALL_DIR (branch: $BRANCH)"

# ── System deps ─────────────────────────────────────────────────────────
log "Installing system packages..."
apt-get update -qq
apt-get install -y -qq git curl nginx certbot python3-certbot-nginx ufw >/dev/null
ok "System packages installed"

# ── Clone repo ──────────────────────────────────────────────────────────
log "Cloning $REPO @ $BRANCH..."
rm -rf "$INSTALL_DIR"
git clone --branch "$BRANCH" --depth 1 "$REPO" "$INSTALL_DIR"
cd "$INSTALL_DIR"
ok "Repo cloned"

# ── Generate .env.production ────────────────────────────────────────────
log "Generating .env.production..."
cat > .env.production <<ENVEOF
# Generated by install.sh on $(date -u)
ZOLAI_API_HOST=0.0.0.0
ZOLAI_API_PORT=8000
ZOLAI_DATA_ROOT=/app/data
ZOLAI_ENGINE_MODE=hybrid
ZOLAI_API_AUTH=enforce
ZOLAI_AUTH_SESSIONS=on
ZOLAI_SESSION_TTL_HOURS=12
ZOLAI_LOG_LEVEL=INFO
ZOLAI_CORS_ORIGINS=*
ZOLAI_CB_ENABLED=true
ZOLAI_CB_FAILURE_THRESHOLD=5
ZOLAI_CB_TIMEOUT=30
ZOLAI_CB_SUCCESS_THRESHOLD=2
ZOLAI_NOTIFICATIONS_ENABLED=true

# Brain API (update these)
AI_BRAIN_URL=https://brain.pcore-system.site/v1
AI_BRAIN_API_KEY=CHANGE_ME

# SMTP (update these)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_TLS=true
SMTP_SSL=true
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-app-password
SMTP_FROM=pcore.system@gmail.com
ADMIN_EMAILS=your-email@gmail.com

# Postgres (optional - leave empty for SQLite)
ZOLAI_PG_URL=
ENVEOF
ok ".env.production created (EDIT IT: vim .env.production)"

# ── Build & Deploy ──────────────────────────────────────────────────────
if [[ "$SKIP_BUILD" == "false" ]]; then
    log "Building Docker image..."
    docker compose -f docker-compose.prod.yml build --no-cache api
    ok "Build complete"
fi

log "Starting containers..."
docker compose -f docker-compose.prod.yml up -d --force-recreate api

log "Waiting for API health..."
for i in {1..60}; do
    curl -sf http://127.0.0.1:8001/api/v1/health >/dev/null 2>&1 && { ok "API healthy"; break; }
    [[ $i -eq 60 ]] && { err "API failed to start"; docker logs zolai-core-api-1 --tail 50; exit 1; }
    sleep 2
done

# ── Nginx + SSL ─────────────────────────────────────────────────────────
if [[ "$SKIP_SSL" == "false" ]]; then
    log "Configuring Nginx + SSL for $DOMAIN..."
    cat > /etc/nginx/sites-available/zolai-api <<NGINXEOF
server {
    listen 80;
    server_name $DOMAIN;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://\$host\$request_uri; }
}
NGINXEOF
    ln -sf /etc/nginx/sites-available/zolai-api /etc/nginx/sites-enabled/
    nginx -t && systemctl reload nginx

    if [[ -n "$EMAIL" ]]; then
        certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL" --redirect
        ok "SSL certificate installed"
    else
        warn "Skipping certbot (no email provided)"
    fi
else
    warn "SSL skipped (--no-ssl)"
    cat > /etc/nginx/sites-available/zolai-api <<NGINXEOF
server {
    listen 80;
    server_name $DOMAIN;
    location / { proxy_pass http://127.0.0.1:8001; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; }
}
NGINXEOF
    ln -sf /etc/nginx/sites-available/zolai-api /etc/nginx/sites-enabled/
    nginx -t && systemctl reload nginx
fi

# ── Firewall ────────────────────────────────────────────────────────────
ufw allow 22/tcp; ufw allow 80/tcp; ufw allow 443/tcp; ufw --force enable >/dev/null
ok "Firewall configured"

# ── Verify ──────────────────────────────────────────────────────────────
log "Running verification..."
sleep 3
curl -sf "https://$DOMAIN/api/v1/health" >/dev/null && ok "HTTPS health OK" || warn "HTTPS check failed (check DNS/SSL)"

# ── Summary ─────────────────────────────────────────────────────────────
echo
ok "Install complete!"
echo
echo "  API:        https://$DOMAIN/api/v1"
echo "  Health:     https://$DOMAIN/api/v1/health"
echo "  Assistant:  POST https://$DOMAIN/api/v1/assistant/chat"
echo "  Admin:      https://$DOMAIN/api/v1/admin"
echo
echo "  Config:     $INSTALL_DIR/.env.production  (EDIT ME)"
echo "  Logs:       docker logs -f zolai-core-api-1"
echo "  Shell:      docker exec -it zolai-core-api-1 bash"
echo
warn "IMPORTANT: Edit $INSTALL_DIR/.env.production with real API keys!"
warn "Then: cd $INSTALL_DIR && docker compose -f docker-compose.prod.yml restart api"
