"""Zolai API package."""

from .auth_session_router import router as auth_session_router
from .session_auth import (
    LoginRejected,
    authenticate,
    change_password,
    create_user,
    ensure_user_session_tables,
    generate_session_token,
    get_user,
    hash_password,
    hash_token,
    issue_session,
    list_user_sessions,
    list_users,
    login,
    login_rate_limit_rpm,
    login_rate_limit_user_rpm,
    normalize_username,
    record_audit,
    resolve_session,
    revoke_session,
    revoke_user_sessions,
    session_ttl_hours,
    sessions_enabled,
    set_user_enabled,
    set_user_role,
    validate_password,
    verify_login,
    verify_password_hash,
)

__all__ = [
    "LoginRejected",
    "auth_session_router",
    "authenticate",
    "change_password",
    "create_user",
    "ensure_user_session_tables",
    "generate_session_token",
    "get_user",
    "hash_password",
    "hash_token",
    "issue_session",
    "list_user_sessions",
    "list_users",
    "login",
    "login_rate_limit_rpm",
    "login_rate_limit_user_rpm",
    "normalize_username",
    "record_audit",
    "resolve_session",
    "revoke_session",
    "revoke_user_sessions",
    "session_ttl_hours",
    "sessions_enabled",
    "set_user_enabled",
    "set_user_role",
    "validate_password",
    "verify_login",
    "verify_password_hash",
]
